
#for some time issue
#   ?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emrys_prod?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: emrys_prod_user
    password: rojaya
    initialization-mode: always       # for initialization of database
#    platform: prod                   #for this to work create data-prod.sql file in resources folder

  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySqL5InnoDBDialect
      database: mysql
      show-sql: false
